### ISSUE TITLE
ModuleNotFoundError: No module named 'sp_iotsim'

### ISSUE THREAD

**Issue by watturkara** [BostonUniversitySeniorDesign/2020-sensor-miniproject#1]
I tried running the instructions as documented in the readme, but after running `python ws_server.py,` I received the following error:
```
Traceback (most recent call last):
  File "ws_server.py", line 10, in <module>
    from sp_iotsim import iot_handler
ModuleNotFoundError: No module named 'sp_iotsim'
``` 

Not sure if this is just something to do with my setup or if others will experience this as well, but the way I resolved this was by adding the following to ws_server.py above the other import statements at the beginning of the file:

<pre>
#!/usr/bin/env python3
"""
WebSockets server
"""

<b>import sys
sys.path.append('/path/to/your/repo/2020-sensor-miniproject/src')</b>
import argparse

.
.
.
</pre>

Please let me know if this is something I should not have done/if there is something I am doing wrong.

**Comment by scivision** [comment]
Thanks--normally we avoid using `sys.path.append` as it can cause namespace clashes where the program becomes unrunnable.
A one-time command makes the package usable:

```sh
python -m pip install -e 2020-sensor-miniproject
```
Or if already in that directory
```
python -m pip install -e .
```

the "-e" makes Python use a live copy of the code in that directory.
